# Xing and Shu, 2005: case 5.3
--- !Config

# spatial information
spatial:
  domain: [0.0, 2.0, 0.0, 1.0]  # [west, east, south, north]
  discretization: [2000, 1000]      # [N_{west<->east}, N_{north<->south}]

# temporal control, including writting result during a simulation
temporal:
  output: ["t_start t_end n_saves", 0., 0.6, 5]
  scheme: "SSP-RK2"

# boundary conditions
boundary:
  west:
    types: ["outflow", "outflow", "outflow"]   # periodic/extrap/outflow/const
    values: [null, null, null]              # only used by "const" type BC
  east:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]
  north:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]
  south:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]

# initial condition
initial:
  file: "initial.nc"
  keys: ["w", "hu", "hv"]

# topography
topography:
  file: "topo.nc"       # relative to case folder or absolute path
  key: elevation        # the corresponding variable name in the NetCDF file

# other parameters
parameters:
  gravity: 9.81  # gravity (m^2/s)
  theta: 1.0  # control numerical dissipation
  dry tolerance: 1.0e-6  # dry tolerance

# any Python script that should be executed prior running the solver
prehook: null
