--- !Config

# spatial information
spatial:
  domain: [0.0, 1.0, 0.0, 1.0]  # [west, east, south, north]
  discretization: [10, 10]      # [N_{west<->east}, N_{north<->south}]

# temporal control, including writting result during a simulation
temporal:
  start: 0.0
  end: 1.0
  output: ["every", 0.1]  # ["at", [T1, T2, ...]] or ["every", delta T]
  scheme: "RK4"           # RK2, RK4, Euler

# boundary conditions
boundary:
  west:
    types: ["extrap", "extrap", "extrap"]   # periodic/extrap/outflow/const
    values: [null, null, null]              # only used by "const" type BC
  east:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  north:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  south:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]

# initial condition
initial:
  file: "initial.nc"       # relative to case folder or absolute path
  keys: [w, hu, hv]     # the corresponding variable names in the NetCDF file
  values: null          # alternativelt, specify a length-3 list for constants

# topography
topography:
  file: "topo.nc"       # relative to case folder or absolute path
  key: elevation        # the corresponding variable name in the NetCDF file

# other parameters
parameters:
  gravity: 9.81  # gravity (m^2/s)
  theta: 1.0  # control numerical dissipation
  drytol: 1.0e-4  # dry tolerance

# any Python script that should be executed prior running the solver
prehook: null
