# Xing and Shu, 2005: case 4.3 & eps=0.2
--- !Config

# spatial information
spatial:
  domain: [0.0, 2.0, 0.0, 1.0]
  discretization: [200, 100]

# temporal control, including writting result during a simulation
temporal:
  output: ["t_start every_seconds multiple", 0., 0.01, 20]
  scheme: "SSP-RK2"

# boundary conditions
boundary:
  west:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  east:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  north:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  south:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]

# initial condition
initial:
  file: "initial.h5"
  keys: ["w", "hu", "hv"]
  xykeys: ["x", "y"]

# topography
topography:
  file: "topo.h5"       # relative to case folder or absolute path
  key: elevation        # the corresponding variable name in the NetCDF file
  xykeys: ["x", "y"]

# other parameters
parameters:
  gravity: 9.81   # gravity (m/s^2)

# any Python script that should be executed prior running the solver
prehook: null
