# Radially-symmetric motion in a paraboloid (Delestre et al., 2013, sec. 4.2.2)
---

# domain information
domain:
    west: 0.0             # a float; x-coordinate of the left boundary
    east: 4.0            # a float; x-coordinate of the right boundary
    south: 0.0            # a float; y-coordinate of the top boundary
    north: 4.0           # a float; y-coordinate of the bottom boundary

# information regarding spatial discretization
discretization:
    Nx: 500            # in integer; number of cells in west-east direction
    Ny: 500            # in integer; number of cells in north-south direction

# boundary conditions
# options for type: periodic, extrap, const
# the key "values" is only used by "const" type BC
boundary conditions:
    west:
        types: [outflow, outflow, outflow]
        values: [null, null, null]
    east:
        types: [outflow, outflow, outflow]
        values: [null, null, null]
    north:
        types: [outflow, outflow, outflow]
        values: [null, null, null]
    south:
        types: [outflow, outflow, outflow]
        values: [null, null, null]

# control of outputing time-series data
output time:
    bg: 0.0
    ed: 2.242850732733187
    step: 0.28035634159164835

# gravity (m^2/s)
gravity: 9.81

# topography
topography:
    file: topo.nc         # relative to case folder or absolute path
    key: elevation        # the corresponding variable name in the NetCDF file

# initial condition
ic:
    file: initial.nc      # relative to case folder or absolute path
    keys: [w, hu, hv]     # the corresponding variable names in the NetCDF file
    values: null          # alternativelt, specify a length-3 list for constants

# any Python script that should be executed first
# relative path or absolute path begining wiht "/"
prehook: create_data.py

# use RK4
temporal: RK4

# control numerical dissipation
theta: 1.0

# dry tolerance
drytol: 1.0e-4
