# Radially-symmetric motion in a paraboloid (Delestre et al., 2013, sec. 4.2.2)
--- !Config

# spatial information
spatial:
  domain: [0.0, 4.0, 0.0, 4.0]
  discretization: [500, 500]

# temporal control, including writting result during a simulation
temporal:
  start: 0.0
  end: 2.242850732733187
  output: ["every", 0.28035634159164835]
  scheme: "RK2"

# boundary conditions
boundary:
  west:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]
  east:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]
  north:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]
  south:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]

# initial condition
initial:
  file: "initial.nc"
  keys: ["w", "hu", "hv"]

# topography
topography:
  file: "topo.nc"       # relative to case folder or absolute path
  key: elevation        # the corresponding variable name in the NetCDF file

# other parameters
parameters:
  gravity: 9.81   # gravity (m/s^2)
  theta: 1.0      # control numerical dissipation
  drytol: 1.0e-4  # dry tolerance

# any Python script that should be executed prior running the solver
prehook: null
