# Xing and Shu, 2005: case 4.4
--- !Config

# spatial information
spatial:
  domain: [0.0, 1500.0, 0.0, 300.0]
  discretization: [500, 200]

# temporal control, including writting result during a simulation
temporal:
  output: ["t_start t_end n_saves", 0., 60., 4]
  scheme: "SSP-RK2"

# boundary conditions
boundary:
  west:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  east:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  north:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  south:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]

# initial condition
initial:
  file: "initial.nc"
  keys: ["w", "hu", "hv"]

# topography
topography:
  file: "topo.nc"       # relative to case folder or absolute path
  key: elevation        # the corresponding variable name in the NetCDF file

# other parameters
parameters:
  gravity: 9.81   # gravity (m/s^2)

# any Python script that should be executed prior running the solver
prehook: null
