name: torchswe-cmake
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - abseil-cpp=20210324.2
  - alsa-lib=1.2.3.2
  - aom=3.3.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - astroid=2.11.4
  - asttokens=2.0.5
  - attrs=21.4.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - binutils=2.36.1
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bleach=5.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-compiler=1.5.0
  - ca-certificates=2022.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2022.9.24
  - cffi=1.15.0
  - cfgv=3.3.1
  - cftime=1.6.0
  - clang=13.0.1
  - clang-13=13.0.1
  - clang-format=13.0.1
  - clang-format-13=13.0.1
  - clang-tools=13.0.1
  - cmake=3.23.1
  - colorama=0.4.4
  - coverage=6.4.4
  - cudatoolkit=11.5.1
  - cudnn=8.2.1.32
  - cupy=10.4.0
  - curl=7.83.0
  - cutensor=1.5.0.3
  - cxx-compiler=1.5.0
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.4
  - distlib=0.3.5
  - distro=1.6.0
  - double-conversion=3.2.0
  - eigen=3.4.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.8
  - fastrlock=0.8
  - ffmpeg=4.4.1
  - filelock=3.8.0
  - flake8=4.0.1
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - gcc=10.4.0
  - gcc_impl_linux-64=10.4.0
  - gcc_linux-64=10.4.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.70.2
  - glib-tools=2.70.2
  - glog=0.6.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - grpc-cpp=1.43.2
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - gxx=10.4.0
  - gxx_impl_linux-64=10.4.0
  - gxx_linux-64=10.4.0
  - h5py=3.6.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - identify=2.5.5
  - imageio=2.19.0
  - importlib-metadata=4.11.3
  - importlib_resources=5.7.1
  - iniconfig=1.1.1
  - ipycanvas=0.12.0
  - ipyevents=2.0.1
  - ipykernel=6.13.0
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipyvtklink=0.2.2
  - ipywidgets=7.7.0
  - isort=5.10.1
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsoncpp=1.9.5
  - jsonschema=4.5.1
  - jupyter=1.0.0
  - jupyter_client=7.3.1
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.0
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcbor=0.9.0
  - libclang=13.0.1
  - libclang-cpp13=13.0.1
  - libcrc32c=1.1.2
  - libcurl=7.83.0
  - libdeflate=1.10
  - libdrm=2.4.109
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libfido2=1.11.0
  - libgcc-devel_linux-64=10.4.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libglu=9.0.0
  - libgomp=12.1.0
  - libgoogle-cloud=1.36.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=14.2
  - libprotobuf=3.19.4
  - libsanitizer=10.4.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=10.4.0
  - libstdcxx-ng=12.1.0
  - libtheora=1.1.1
  - libthrift=0.16.0
  - libtiff=4.3.0
  - libudev1=249
  - libutf8proc=2.7.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libva=2.14.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=14.0.4
  - loguru=0.6.0
  - lz4-c=1.9.3
  - make=4.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mock=4.0.3
  - mpi=1.0
  - mpi4py=3.1.3
  - munkres=1.1.4
  - mypy=0.971
  - mypy_extensions=0.4.3
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclient=0.6.2
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - nccl=2.12.10.1
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.5.8
  - nettle=3.6
  - ninja=1.11.0
  - nodeenv=1.7.0
  - notebook=6.4.11
  - nspr=4.32
  - nss=3.77
  - numpy=1.23.0
  - openblas=0.3.20
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openmpi=4.1.3
  - openssh=9.0p1
  - openssl=1.1.1q
  - opt-einsum=3.0.0
  - orc=1.7.3
  - orjson=3.6.8
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.2.2
  - platformdirs=2.5.1
  - pluggy=1.0.0
  - pre-commit=2.20.0
  - proj=9.0.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - prompt_toolkit=3.0.29
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - py=1.11.0
  - pyarrow=8.0.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydantic=1.9.0
  - pyflakes=2.4.0
  - pygments=2.12.0
  - pylint=2.13.8
  - pynvml=11.4.1
  - pyparsing=3.0.8
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - pytest-lazy-fixture=0.6.3
  - pytest-mock=3.8.2
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.9
  - pyvista=0.34.0
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.3.0
  - qtconsole-base=5.3.0
  - qtpy=2.1.0
  - re2=2022.02.01
  - readline=8.1.2
  - rhash=1.4.3
  - s2n=1.0.10
  - scikit-build=0.15.0
  - scipy=1.8.0
  - scooby=0.5.12
  - send2trash=1.8.0
  - setuptools=62.1.0
  - six=1.16.0
  - snappy=1.1.9
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - svt-av1=0.9.1
  - sysroot_linux-64=2.17
  - tbb=2021.5.0
  - tbb-devel=2021.5.0
  - terminado=0.13.3
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.1
  - traitlets=5.1.1
  - types-docutils=0.19.1
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - ucx=1.12.1
  - ukkonen=1.0.1
  - unicodedata2=14.0.0
  - utfcpp=3.2.1
  - virtualenv=20.16.5
  - vtk=9.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - wrapt=1.14.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxt=1.2.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - alabaster==0.7.12
    - babel==2.10.3
    - charset-normalizer==2.1.1
    - commonmark==0.9.1
    - docutils==0.19
    - idna==3.4
    - imagesize==1.4.1
    - markdown==3.3.7
    - pydata-sphinx-theme==0.10.1
    - pytz==2022.2.1
    - recommonmark==0.7.1
    - requests==2.28.1
    - snowballstemmer==2.2.0
    - sphinx==5.2.1
    - sphinx-copybutton==0.5.0
    - sphinx-markdown-tables==0.0.16
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - tifffile==2022.8.12
    - urllib3==1.26.12
