# This is a template comtaining all required & optional options.
--- !Config

spatial:
  domain: [-0.1988578658982294, 1.0, -0.3, 0.3]
  discretization: [2001, 2001]

temporal:
  output: ["at", [0.0, 32.0, 59.0, 122.0, 271.0, 486.0, 727.0]]
  scheme: Euler

boundary:
  west:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  east:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  north:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]
  south:
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]

initial:
  # The actual w (elevation) is not be zero. It should be the same as topography
  # elevation. Setting it zero theoretically means it's negative depth. However,
  # the solver will automatically convert initial negative depth to topography
  # elevation, so it's fine to set zero for I.C. in practice.
  values: [0., 0., 0.]

topography:
  file: "topo.h5"
  key: elevation
  xykeys: ["x", "y"]

point source:
  location: [0.0009517784181422018, 0.0]
  times: []
  rates: [1.48e-6]

fluid properties:
  density: 1.
  reference mu: 1.13e-3
  reference temperature: 15.
  ambient temperature: 15.
  nu: 1.13e-3

friction:
  roughness: 0.

parameters:
  dry tolerance: 1.0e-5
