# This is a template comtaining all required & optional options.
--- !Config

# =============================================================================
# Required block: spatial information
# =============================================================================
spatial:

  # required: computaional domain's bounds: [west, east, south, north]
  # ---------------------------------------------------------------------------
  domain: [0.0, 1.0, 0.0, 1.0]

  # required: number of cells in each direction: [west<->east, north<->south]
  # ---------------------------------------------------------------------------
  discretization: [10, 10]

# =============================================================================
# Required block: temporal control, including outputing unsteady solutions
# =============================================================================
temporal:

  # required; choose from one of the following formats
  #     1. ["at", [float, float, float, float...]]
  #     2. ["t_start every_seconds multiple", float, float, int]
  #     3. ["t_start every_steps multiple", float, int, int]
  #     4. ["t_start t_end n_saves", float, float, int]
  #     5. ["t_start t_end no save", float, float]
  #     6. ["t_start n_steps no save", float, int]
  # ---------------------------------------------------------------------------
  output: ["t_start t_end n_saves", 0., 1., 10]

  # optional; the initial time step size if using adaptive time stepping.
  # ---------------------------------------------------------------------------
  dt: 1e-3

  # optional; indicates whether to use adaptive time stepping.
  # ---------------------------------------------------------------------------
  adaptive: true

  # optional; maximum number of iteration in each saving interval
  # ---------------------------------------------------------------------------
  max_iters: 1000000

  # optional; temporal scheme; available options: Euler, SSP-RK2, SSP-RK4
  # ---------------------------------------------------------------------------
  scheme: "SSP-RK2"

# =============================================================================
# Required block: boundary conditions
# =============================================================================
boundary:

  # required; boundry conditions for w, hu, and hv at the west bound
  # ---------------------------------------------------------------------------
  west:

    # required; available types: periodic, extrap, const, inflow, outflow
    types: ["extrap", "extrap", "extrap"]

    # optional; only needed when having const and inflow BCs.
    values: [null, null, null]

  # required; boundry conditions for w, hu, and hv at the east bound
  # ---------------------------------------------------------------------------
  east:

    # required; available types: periodic, extrap, const, inflow, outflow
    types: ["extrap", "extrap", "extrap"]
    values: [null, null, null]

  # required; boundry conditions for w, hu, and hv at the north bound
  # ---------------------------------------------------------------------------
  north:

    # required; available types: periodic, extrap, const, inflow, outflow
    types: ["extrap", "extrap", "extrap"]

    # optional; only needed when having const and inflow BCs.
    values: [null, null, null]

  # required; boundry conditions for w, hu, and hv at the south bound
  # ---------------------------------------------------------------------------
  south:

    # required; available types: periodic, extrap, const, inflow, outflow
    types: ["extrap", "extrap", "extrap"]

    # optional; only needed when having const and inflow BCs.
    values: [null, null, null]

# =============================================================================
# Required block: initial condition
#
# Note
# ----
# Must set either `file` plus `keys` or `values`.
# =============================================================================
initial:

  # see note; the file name/path to a CF-compliant NetCDF file for I.C.
  # ---------------------------------------------------------------------------
  file: "initial.nc"

  # see note; the names/keys of w, hu, and hv datasets in the the NetCDF file.
  # ---------------------------------------------------------------------------
  keys: [w, hu, hv]

  # see note; choose this for constant I.C.
  # ---------------------------------------------------------------------------
  values: null

# =============================================================================
# Required block: topography
# =============================================================================
topography:

  # required; the file name/path to a CF-compliant NetCDF file for topography
  # ---------------------------------------------------------------------------
  file: "topo.nc"

  # required; the name/key for the elevation dataset in the the NetCDF file.
  # ---------------------------------------------------------------------------
  key: elevation

# =============================================================================
# Optional block: point source
#
# Note
# ----
# If this block presents, all the settings under this block must be set.
# =============================================================================
point source:

  # required;the coordinates in x and y of the point source
  # ---------------------------------------------------------------------------
  loc: [0.5, 0.5]

  # required; the times when to switch flow rates and the corresponding rates.
  # `rates` must have a length one greater than that of `time`. For example,
  # if `times` # is [1., 2., 3.], and `rates` is [1., 0.5, 0.1, 0.], this
  # setting means that the rate between T=T0 (T0 determined based on `temporal`
  # configuration) to T=1 seconds is 1.0 m^3/sec; the rate between T=1 to 2
  # seconds is 0.5 m^3/sec; and the rate between T=2 to 3 seconds is 0.1
  # m^3/sec. Finally, a zero flow rate applies to T >= 3.
  # ---------------------------------------------------------------------------
  times: [1., 2., 3.]
  rates: [1., 0.5, 0.1, 0.]

# =============================================================================
# Optional block: other parameters
# =============================================================================
parameters:

  # optional; gravitational acceleration
  # ---------------------------------------------------------------------------
  gravity: 9.81

  # optional; a numerical parameter controlling numerical dissipation
  # ---------------------------------------------------------------------------
  theta: 1.0

  # optional; indicates the upper bound of depths to be considered dry
  # ---------------------------------------------------------------------------
  drytol: 1.0e-4

  # optional; number of ghost cells; current schemes only need 2 ghost cells
  # ---------------------------------------------------------------------------
  ngh: 2

  # optional; after how many steps to print simulation info on screen/stdout
  # ---------------------------------------------------------------------------
  log_steps: 100

  # optional; floating point precision; either "float32" or "float64"
  # ---------------------------------------------------------------------------
  dtype: "float64"

# =============================================================================
# Optional block: a Python script that should be executed prior a simulation
# =============================================================================
prehook: null
