# Kurganov & Petrova, 2007; case 4.2
--- !Config

# spatial information
spatial:
  domain: [-1.0, 1.0, -1.0, 1.0]
  discretization: [400, 400]

# temporal control, including writting result during a simulation
temporal:
  output: ["t_start every_seconds multiple", 0., 1., 4]
  scheme: "SSP-RK2"

# boundary conditions
boundary:
  west:
    types: ["const", "inflow", "inflow"]
    values: [0.25, 0.5, 0.0]
  east:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]
  north:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]
  south:
    types: ["outflow", "outflow", "outflow"]
    values: [null, null, null]

# initial condition
initial:
  file: "initial.nc"
  keys: ["w", "hu", "hv"]

# topography
topography:
  file: "topo.nc"       # relative to case folder or absolute path
  key: elevation        # the corresponding variable name in the NetCDF file

# other parameters
parameters:
  gravity: 2.0   # gravity (m/s^2)
  theta: 1.3      # control numerical dissipation
  dry tolerance: 1.0e-4  # dry tolerance

# any Python script that should be executed prior running the solver
prehook: null
